services:

  db:
    image: postgres:16
    container_name: contractshield-db
    environment:
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: contractshield-backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:devpass@db:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: contractshield-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: